apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "OuJ4krIndY1U5WG6aGLHvva771UwfaQ8p6g7tXSyrDBB9bk7vCU1wzOBE0ufYaXg\nwnk9rgQoZMGTT/1iCzP+prZ7Q1sZ8KLgf7uI88lOOhZJiYl09EaYUaV7DfycQsA3\n+10xEsy+Ivj1wktTUKoyXWsyRDSoxPMZogEz1upd6+c="
